class_name  WeaponEnums
extends RefCounted

# Handles all the enumerations for weapons.
enum SceneKey { PROJECTILE, SECONDARY_PROJECTILE, IMPACT_EFFECT, TRAIL_EFFECT }
enum Type { SLAM, LIGHT_BLADE, WALDOS, ARROW, CHAIN_LIGHTNING, HAILFIRE, SCATTERSTAR, BLACK_HOLE }
enum TargetType { NONE, CLOSEST, HIGHEST_HP, RANDOM, CONTINUOUS, BIGGEST_CLUSTER }